### ISSUE TITLE
Block G Car Park light

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#10]
### Property Details

Block G

### Type of problem?

Repair

### Since when this issue started?

July 2021

### Issue Description?

The car park behind the Block G is dark. Its been reported that the lights are not working. These lights are not covered by Council which maintains most of the lights. 

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
Please have a look why this issue is not resolved? I thought we arrange cherry picker and fixes these lights, are they gone bad again? please update here.

**Comment by jeremydoran** [comment]
I will follow up on this as to why this is still an issue. I am aware that this has been previously look into.

**Comment by jeremydoran** [comment]
I have received confirmation today that this matter has been resolved.
