### ISSUE TITLE
Wrong Payment Reminders and Late fee

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#12]
### Property Details

General Estate

### Type of problem?

Accounts and Payment

### Since when this issue started?

Oct 2021

### Issue Description?

Many of the residents receive Late payment emails, even though they are up to date on their payment. They were asked to pay £90 late fee. Please check why this happened? if this was a mistake then confirm and make sure this doesnt happen again please.
Also provide the process document by which the late fee will be added to the service charges, as there ought to be warning about late payment instead of slapping of £90 right as the first letters are sent.

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
Got the Response from Bradley, he will look into why this happened however following is the process.
The stages are:

 

1.            Issue the demand and obligatory summary of rights

2.            Reminder letter issued circa 14 days after due date

3.            Late payment penalty letter one (1) issued on or around 14 days after the initial reminder letter with a minimum charge of £75 + VAT

4.            Late payment penalty letter two (2) issued on or around 14 days after the letter one (1) with a minimum charge of £125 + VAT

5.            Referral fee letter three (3) issued on or around 14 days after the letter two (2) with a minimum charge of £200 + VAT and account passed on to third party debt recovery

**Comment by theparksilford** [comment]
Close this issue once we are know the reason for the mistake.

**Comment by jeremydoran** [comment]
Letters were sent out by mistake by our accounts team, this matter has now been rectified.
