### ISSUE TITLE
Tree Trimming

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#13]
### Property Details

General Estate

### Type of problem?

Repair

### Since when this issue started?

Oct 2021

### Issue Description?

We need to get the trees trimmed, Please check with Iconic when they going to do it and provide the schedule. The are getting bigger and starts to look bad.

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
Iconic updated me that they have started trimming, but cars in the way. They done but of it and will post the notices to car on monday and try to clear out much on next Thursday 25th Nov.

**Comment by jeremydoran** [comment]
Iconic are scheduled to attend on Thursday 25th November.

**Comment by jeremydoran** [comment]
I'm awaiting confirmation that this went ahead as planned before closing this issue.

**Comment by jeremydoran** [comment]
Iconic have confirmed that this works was completed on 25th November as planned.
