### ISSUE TITLE
Outer concrete on flat has come away

### ISSUE THREAD

**Issue by Corinne2021** [theparksilford/Issues#14]
### Property Details

81 Blackthorn Road Ilford Essex IG1 2NS

### Contact Details

corinneprosper@hotmail.com

### Type of problem?

Repair

### Since when this issue started?

17/11/2021

### Issue Description?

Concrete has come away from the flat on the outer building- concrete found on thr balcony see attached pictures 
![F097337C-77E3-4203-804A-D81C702B11C7](https://user-images.githubusercontent.com/94566394/142272294-3096b581-a46a-43d3-b1a4-e1d4f5c12136.jpeg)
![93500E45-C532-4EC7-9A0E-10F37A337861](https://user-images.githubusercontent.com/94566394/142272318-6995147c-824d-463b-9cd7-fafc52db468d.jpeg)
![789CCFCD-364D-455F-9827-D0C175D3E88F](https://user-images.githubusercontent.com/94566394/142272324-9c72dcf9-355d-4cd2-b0ca-c18e3c6261be.jpeg)

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
RR, Please arrange a visit and do the needful thanks

**Comment by jeremydoran** [comment]
Contractor has been instructed, the contractor will contact the home owner to arrange a suitable date and time shortly.

**Comment by jeremydoran** [comment]
The contractor has advised that they will be sending across a quote for this repair works due to the cost of accessing this area.

**Comment by jeremydoran** [comment]
A quotation for this repair works has been sent to the directors for approval and I have advised that it might be better to wait until we carry out future works on the block to avoid the high cost of repair. The quote is costly due the the effected area being very high and difficult to get to.

**Comment by jeremydoran** [comment]
This repair will be carried out at a future date due to the costs involved getting to the area needed to provide a suitable safe repair.
