### ISSUE TITLE
Mrs Corinne Maronie

### ISSUE THREAD

**Issue by Corinne2021** [theparksilford/Issues#15]
### Property Details

83 Blackthorn Road Ilford Essex IG1 2NS

### Contact Details

corinneprosper@hotmail.com

### Type of problem?

General Issue

### Since when this issue started?

25th December 2021

### Issue Description?

Flat 83 had dumped two mattresses initially in the communal area on Christmas Day. I had to ask the tenants to remove the items due to hygiene and safety and they have now dumped the items in the communal gardens
![image](https://user-images.githubusercontent.com/94566394/147585768-dfc9a401-d339-4b83-b62f-46e81db71b63.jpg)

### Logged By

Leaseholder or FreeHolder

**Comment by Corinne2021** [comment]
Apologies for the quality of the picture but the items are left in the communal gardens at the back of the block

**Comment by theparksilford** [comment]
Tried knocking the door on 83 but they were not there. I’ll try again tomorrow. @jeremydoran please communicate with the flat owners. Here is a better copy. 

![Uploading 6E7548C5-7454-4605-8C74-0FB1FCB710BB.jpeg…]()

**Comment by jeremydoran** [comment]
I have now spoken with the landlord today and he has advised that he will contact the tenant today and ask when the mattress will be removed.

**Comment by jeremydoran** [comment]
I have spoken to the landlord today following on from my previous conversation about the mattress. The landlord advised he will be going to the property tomorrow to speak with the tenants and advise that this behaviour is unacceptable and that this needs to be removed straight away. 

I have asked for confirmation of this and will follow up accordingly.

**Comment by theparksilford** [comment]
This is still not removed. Ping them when you can please.

**Comment by theparksilford** [comment]
I think we need to charge them now. It’s still not moved out. Tell them their accounts will be charged £100 at@4pm Monday if by that time it’s not removed. No if not buts and no chances. They given enough changes and time.

**Comment by theparksilford** [comment]
We will also report it to the council. If they move it back, they need to tell us when it will be taken away and provide proof and put it also on the items.

**Comment by theparksilford** [comment]
Has this been actioned upon? I want confirmation of the charge to the service charge account so that I can arrange pickup of this stuff.

**Comment by jeremydoran** [comment]
I spoke with the landlord yesterday who apologised on behalf of his tenants and advised that this collection is arranged with Redbridge Council on Friday 14/01/2021.

**Comment by theparksilford** [comment]
It has been collected so closing the issue.
