### ISSUE TITLE
Dumping by 205 Mr. Bola

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#17]
### Property Details

205 blackthorn road

### Type of problem?

Cleaning

### Since when this issue started?

11 Jan 2022

### Issue Description?

The mattress and other stuff came from 205. It was dumped by the owner himself.  I told them that it’s not allowed and he has done this previously however he said it will get it removed next day. Then he said he booked it with council who will collect today 24 Jan. However council only took the mattress and other stuff (bed frame) is still there. We have given him enough warnings. Please convey the message that If he doesn’t remove it in next couple of days then we will get it removed and charge him £100. Residents are complaining and he has had enough time to get it cleared. 
![056D33EB-02F1-4A75-9658-C0DA724872F8](https://user-images.githubusercontent.com/85579935/150836390-2bbee6d8-4c43-4d51-b643-a3c2c16f00e2.png)
![7569EE47-E1A0-4FBE-A41C-6CBAE61865EC](https://user-images.githubusercontent.com/85579935/150836415-642efef0-1571-4a2a-b5ba-6ae10e04ca67.jpeg)

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
The landlord has been contacted about this and has been asked to speaks to his tenants to get these items removed straight away.

I will follow this up accordingly.

**Comment by theparksilford** [comment]
He thrown the stuff himself.  After I confronted  he arranged it with the council.  The stuff is out since 11th Jan so we need to give them specific time(1 day) and tell them the video and information will be passed to the council and £100 fee will also be charged to their service charge as we will get it collected.

**Comment by theparksilford** [comment]
The resident came to my house and explained that he did arrange it with the council but they pick up only mattress. He had to arrange it again and pay for it. Council will pick up on Monday.

**Comment by theparksilford** [comment]
This has been removed so closing it
