### ISSUE TITLE
6 Cedar close dumping and fence

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#23]
### Property Details

6 cedar close

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

20 feb 2022

### Issue Description?

Looks like 6 cedar close tenants moved out and left their rubbish outside the house. Please contact the owner and ask them to remove it. Remind them not to dump it in the bin area, find the local tip and drop it there. 
also their right hand side fence is broken due to the heavy wind and they need to get it fixed. 
![04319034-ACA8-4145-9E28-73BFF03CC163](https://user-images.githubusercontent.com/85579935/154978402-246fc9b1-55c6-41bf-becc-d282e3a4f826.jpeg)
![0B6F39ED-0EB5-4C10-AEBD-BA3ABB676011](https://user-images.githubusercontent.com/85579935/154978502-40d3bfc8-8637-47cc-b4b3-18c15a2a8034.jpeg)

### Logged By

Directors

**Comment by theparksilford** [comment]
Have we communicated?

**Comment by jeremydoran** [comment]
I have called the landlord to ask if the fence has been fixed as promised, I was advised that the tenants have now been evicted from the property and fence should have been fixed. 

I will call back tomorrow to confirm the situation.

**Comment by jeremydoran** [comment]
The landlord was unable to confirm if this fence has been fixed at this moment, I will follow this up next week.

**Comment by theparksilford** [comment]
Well I can confirm it’s not fixed.

**Comment by jeremydoran** [comment]
This has now been reported to Mears Group who rent the property. 
This has been logged (Ref: 61335) and I await an update on this issue.

**Comment by jeremydoran** [comment]
I have been advised that the landlord lives abroad by the letting agent. The letting agent can be contacted directly on 07984428937. 
I have been advised that this property has previously been rented to Mears Group who can be contacted on 020 8354 5500. Mears Group are arranging for repair works to be carried out currently including the repair works to the fence.

**Comment by jeremydoran** [comment]
Left another message with Mears Group (0330 678 0277) and spoke with Ese. I have left a message for the property manager to call me back.

**Comment by jeremydoran** [comment]
Mears Group have advised that the works will start on 1st June however they cannot provide me with an exact date as to when the fence will be repaired.

**Comment by theparksilford** [comment]
No work is being done right now. They finished doing work last week I believe so what now?

**Comment by jeremydoran** [comment]
This has been reported to Ebby at Mears Group and I await a response with an update.

**Comment by jeremydoran** [comment]
I have spoken to Ebby today from Mears Group who advised that this is still work in progress and he hopes to have the property let back out by 1st August with all repairs carried out including the fence repair.

**Comment by theparksilford** [comment]
This is still not fixed.

**Comment by jeremydoran** [comment]
I have followed this up with Ebby from Mears Group today.

**Comment by theparksilford** [comment]
It’s fixed now
