### ISSUE TITLE
Dumping at L&Q site

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#24]
### Property Details

L&Q flats 

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

20 mar 2022

### Issue Description?

Dumping of sofa and mattress at the usual site of L@Q site

![115F13F4-3191-4988-8866-BAFF2314D21A](https://user-images.githubusercontent.com/85579935/159275570-c416fe35-689a-4bc4-8923-6d75050b2452.jpeg)

please ask them to arrange it. 

### Logged By

Directors

**Comment by jeremydoran** [comment]
These items have now been removed by L&Q

**Comment by theparksilford** [comment]
Yes it was cleared but now a mattress dumped again. But we will open new issue in couple of weeks so they can clear with other things.
