### ISSUE TITLE
Poor gardening at The Parks

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#26]
### Property Details

22 Blackthorn Road

### Contact Details

Rgthrow@gmail.com

### Type of problem?

Ground Maintenance

### Since when this issue started?

5 May 2022

### Issue Description?

No hedges/shrubs have been trimmed. No weeding done of flower beds

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
Closing this issue as this is a duplicate of other issue where photos have been posted.
