### ISSUE TITLE
Grass not cut / poor gardening at The Parks

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#32]
### Property Details

Grass behind 83 to 93 Blackthorn Road flats

### Contact Details

Rgthrow@gmail.com

### Type of problem?

Ground Maintenance

### Since when this issue started?

2022

### Issue Description?

Grass has not been cut behind this apartment block in 2022. This was also reported last week but no action has been taken.
![0228C3AF-723B-4B10-9F28-C2A4AEE2B7AC](https://user-images.githubusercontent.com/105227854/169034830-8dea7a95-3ceb-47bb-b879-ddb90666bcac.jpeg)

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
Duplicate. Use other issue.
