### ISSUE TITLE
Dumping by 65 blackthorn road

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#34]
### Property Details

55 blackthorn road

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

15 June 2022

### Issue Description?

Dumping pallet from 65. Please contact and ask them to clear out. I tried ringing the door but no replies. 
![F15D0FFC-E2E7-443A-8800-2B0625C1201F](https://user-images.githubusercontent.com/85579935/173874936-4575ce86-2310-439f-98c6-4f122c9532a1.jpeg)

### Logged By

Directors

**Comment by theparksilford** [comment]
Luckily this has been removed by some other resident to be used in their project. However we should still communicate with 65 to tell them this is now allowed.

**Comment by jeremydoran** [comment]
The leaseholder has now been contacted and sent this picture and asked that this gets removed asap. 
The leaseholder has been contacted by email as we do not hold any telephone number.

**Comment by theparksilford** [comment]
This also was removed as another resident used it for his project. Closing it

**Comment by jeremydoran** [comment]
I have followed this up on email as I haven't received any response.
