### ISSUE TITLE
205 dumping regularly

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#36]
### Property Details

205 blackthorn road

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

23 June 2022

### Issue Description?

This is going on for sometime now. They keep dumping stuff and when we tell them they arrange to pick it up. There shouldn’t be any dumping and we need to stop this cat and mouse game. 
please see these two videos and send it to their flat owners and talk to them. There is strictly no dumping allowed. It was dumped 23 June night and still not cleared. But when we show them they will say they were about to pick it up. 

![30A62CE4-A9B9-4A7C-B8B2-B850E9EE32CF](https://user-images.githubusercontent.com/85579935/175771934-e22d8baf-c3dc-4e58-916c-0cb51992fa80.jpeg)
![41184CCC-B4E3-46BB-B18E-BC37813AD134](https://user-images.githubusercontent.com/85579935/175771954-08649a7a-35d7-4cd7-8c89-bcac7236fb82.jpeg)

Videos

https://share.icloud.com/photos/0a7RphXH_WP6UaCPiQieh9GTg

https://share.icloud.com/photos/059wBPvn9s2JYGVOO8UIXylxQ

### Logged By

Directors

**Comment by jeremydoran** [comment]
I have now emailed the landlord about this and I await a response.

**Comment by theparksilford** [comment]
Both the items were taken away by other residents for their own use so al fine from removal point of view however the message should be received about no dumping policy.

**Comment by jeremydoran** [comment]
The letting agent has confirmed she has advised the tenant to stop this.

**Comment by theparksilford** [comment]
Thanks
