### ISSUE TITLE
Block A intercom not working

### ISSUE THREAD

**Issue by togdheer** [theparksilford/Issues#37]
### Property Details

Block A

### Contact Details

cruisecontroll@hotmail.com

### Type of problem?

Repair

### Since when this issue started?

Intercom has been acting up for a week

### Issue Description?

Issue 1

We can hear the intercom buzzing when people press the button but we can't let people in from our handsets in our flats. It's the same for a number of flats in block A. 

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
A contractor has been notified and is just awaiting for a suitable contact number before he makes an appointment to attend.

**Comment by theparksilford** [comment]
Is this resolved? If not, why not? Please get this fixed asap.

**Comment by jeremydoran** [comment]
Please respond so we can get this issue looked at should this still be a problem.

The contractor would need this information before attending as this issue might be to do with your own handset.

**Comment by theparksilford** [comment]
@togdheer please provide your contact details as well anyone else facing issue and their door number.

**Comment by jeremydoran** [comment]
The intercom has been checked and was found to be working correctly. We would need your contact details to investigate this further. Should you wish to contact me then please return one of my call or one of my emails.

**Comment by theparksilford** [comment]
Residents still having issues. I have asked them to contact you and provide their details.

**Comment by humzaakhtar1** [comment]
Intercom not working in block 197-211 no ones buzzer is working

**Comment by theparksilford** [comment]
> Intercom not working in block 197-211 no ones buzzer is working

We should create new issue for this block. I’ll create and move this there.

**Comment by jeremydoran** [comment]
Thank you.
