### ISSUE TITLE
Communal lights Block A

### ISSUE THREAD

**Issue by togdheer** [theparksilford/Issues#38]
### Property Details

Block A

### Contact Details

cruisecontroll@hotmail.com

### Type of problem?

Repair

### Since when this issue started?

3 to 4 days

### Issue Description?

The communal lights are constantly on (staying on) 24 hours a day when they should be coming on when switched on for a few seconds.

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
A contractor has been notified and will be attending to this shortly.

**Comment by togdheer** [comment]
The lights are still on!

**Comment by jeremydoran** [comment]
This has been followed up with the contractor who has been asked to attend to this asap.

**Comment by togdheer** [comment]
The lights are still on. With the high costs of electricity this should have been treated with urgency to save leaseholders costs.

**Comment by jeremydoran** [comment]
The electrician did attend to this recently, the electrician will attend again today.

**Comment by jeremydoran** [comment]
This has now been resolved today.

**Comment by togdheer** [comment]
The lights are still on !

![dsffw344](https://user-images.githubusercontent.com/109242920/181627430-452f20f7-a971-47d8-b857-d8bef544b77f.jpg)

**Comment by togdheer** [comment]
> This has now been resolved today.

Care to explain what's been resolved?

**Comment by jeremydoran** [comment]
The communal lights have been turned off and are not on permanently.

**Comment by togdheer** [comment]
> The communal lights have been turned off and are not on permanently.

The lights are STILL on permanently as I explained above. Would you like a video? 

https://user-images.githubusercontent.com/109242920/181933814-22233d0f-8133-4e96-af0a-fa9ef3c0d03e.mp4

**Comment by jeremydoran** [comment]
Thank you for letting me know, I passed this to the contractor and have asked that they re-attend urgently.

**Comment by theparksilford** [comment]
Why is this getting resolved? Do we understand the issue here? Please find out, when the light should come up, for how long and during what time? Currently as resident mentions it’s ON 24/7

**Comment by togdheer** [comment]
The lights have gone off. When the switch is pressed the lights come on and stay on for over 2 minutes now instead of the 20 seconds they used to stay on for.

**Comment by theparksilford** [comment]
2 minutes is ok I suppose. 20 seconds will be very annoying specially for high floors. Don’t think we saving much money here.

**Comment by jeremydoran** [comment]
This has been now been resolved and the light are working correctly.
