### ISSUE TITLE
Fridge dumped by 181

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#39]
### Property Details

181 blackthorn road

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

13 July 2022

### Issue Description?

Fridge dumped from 181. Looks like a worker who visited and just dumped the fridge outside. Please let the owner know and ask it to be removed asap

![5E163210-A068-47DB-97F1-770DD4C6EE3C](https://user-images.githubusercontent.com/85579935/178985867-56d5f3a1-9fbb-4a78-856f-9d2888525bda.jpeg)
![84C1975A-CFEE-4726-9656-5628AB145D7D](https://user-images.githubusercontent.com/85579935/178987812-4e75a460-3372-4665-a56d-46170a4c2eeb.png)

### Logged By

Directors

**Comment by theparksilford** [comment]
What’s the update?

**Comment by jeremydoran** [comment]
The client has advised that this should now have been removed. Please can you confirm if this is the case?

**Comment by jeremydoran** [comment]
This has now been rebooked with the council to be removed.

**Comment by jeremydoran** [comment]
This has been re-booked for collection on Monday 8th August.

**Comment by theparksilford** [comment]
Still not gone. It’s been 25 days now. This should’ve been removed by now.

**Comment by theparksilford** [comment]
This is gone thanks.

**Comment by theparksilford** [comment]
Still there, not removed. Council did visit and picked up some houses bulk rubbish but not fridge. If it was booked with council they should chase them. Regards,Shahjahan Durrani---- On Mon, 25 Jul 2022 12:02:43 +0100  ***@***.***> wrote ---- 
The client has advised that this should now have been removed. Please can you confirm if this is the case?
