### ISSUE TITLE
Block Door issue

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#4]
### Property Details

37 Blackthorn Rd

### Contact Details

test@test.com

### Type of problem?

Repair

### Since when this issue started?

May 2021

### Issue Description?

Communal Door not locking. Issue with door not closing. Contractor has ordered spare parts to fix issue.

### Logged By

Tenant in a flat

**Comment by theparksilford** [comment]
Update by directors: 12th Nov 2021 Still not resolved. Still waiting for the contractor acquire the part.

**Comment by theparksilford** [comment]
I visited the door and looks like the original part issue has been resolved however, the door is broken and doesn't lock. This needs to be fixed asap.

**Comment by jeremydoran** [comment]
Parts have been on order for quite some time now which had to be ordered in from the manufacturer, these part have arrived this afternoon. 

The contractor will now be attending with this part to resolve this issue on Monday (22.11.21).

**Comment by jeremydoran** [comment]
This door has been repaired however I am now aware that the door cannot be accessed using the push button and the door does not self close. The contractor has been made aware and I await an urgent update on this.

**Comment by jeremydoran** [comment]
This issues has been resolved,  the contractor has attended and check the door and found that there were no more faults.
