### ISSUE TITLE
Spilt paint by bin store on Lawson Close

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#40]
### Property Details

1-35 Lawson Close

### Contact Details

Rgthrow@gmail. Com

### Type of problem?

Ground Maintenance

### Since when this issue started?

30 July 2022

### Issue Description?

A large amount of white paint covering the whole walkway has been spilt next to the bin store on Lawson Close blocking the pedestrian entrance to the estate. 

Also a cooker has been dumped there.

please sort this problem out and or contact L and Q

### Logged By

Leaseholder or FreeHolder

**Comment by Thurgarton66** [comment]
![Uploading 3551A4E8-441E-44A1-9981-E9E887457166.jpeg…
![88ECE008-0103-4DD9-9D83-A02971860956](https://user-images.githubusercontent.com/105227854/182024435-c4d30512-c981-4825-8056-0d1bdd1e9549.jpeg)
]()

**Comment by Thurgarton66** [comment]
Photos uploaded

**Comment by theparksilford** [comment]
@jeremydoran please act on it. Both the bin store are in bad state. One of them being ignore by council perhaps it’s inaccessible(also has mattress inside). 
Please arrange urgently with L&Q.
If they take time then tell them we will clear it and then bill them. Also the paint on the floor needs to cleared out. 

![C33FB7EF-6186-4416-95BA-04637835F324](https://user-images.githubusercontent.com/85579935/182470532-89a2fc82-bd8b-4850-8b15-88c659c1c6b8.jpeg)
![37C6F0B2-CC38-4947-B8FE-96FA691281E0](https://user-images.githubusercontent.com/85579935/182470544-23cd08ad-18c7-4c3f-860e-1d7ef532727c.jpeg)

**Comment by theparksilford** [comment]
The overflowing bin got cleared thanks to iconic. 
So we need to ask L&Q to,
1. Clear the dumping outside both the bin stores
2. Clean the paint on the floor
3. Look into their gardening as it looks like it’s not maintain for a few weeks. 
![EB553B7A-5821-45E3-B76C-2D704E176F6C](https://user-images.githubusercontent.com/85579935/182818351-62b738b5-a730-4036-91fa-64a38d2b1113.jpeg)
![6EF8A60B-7FDC-4090-B696-38582620C2DB](https://user-images.githubusercontent.com/85579935/182818379-bdddcbd2-d2a5-412b-9f7f-28421f827e04.jpeg)
![D35D796D-1A60-4FFF-A685-71DD65BF0E83](https://user-images.githubusercontent.com/85579935/182818457-5689ae86-8e88-4270-8855-61f080c12143.jpeg)

Just checked and Jeremy is on leave so report it to L&Q directly if we can?

**Comment by theparksilford** [comment]
@jeremydoran please remind L&Q to clear the pain off the floor too. Looks like they clear the dumping and arranged the bin room.

**Comment by jeremydoran** [comment]
I have followed this up with L&Q today again.

**Comment by jeremydoran** [comment]
This was followed up again yesterday with L&Q, I phoned have asked the supervisor to look into this urgently.

**Comment by jeremydoran** [comment]
I have followed this up with L&Q again and await a response.

**Comment by jeremydoran** [comment]
This has been escalated at L&Q, the property manager for L&Q has been uncountable and also her manager. I have raised a full complaint and now the area manager should be contacting me regarding this.

**Comment by jeremydoran** [comment]
This has now been attended to by L&Q Housing.
