### ISSUE TITLE
Missing brick cap on boundary column

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#41]
### Property Details

The Parks perimeter wall Loxford Lane

### Contact Details

Rgthrow@gmail.com

### Type of problem?

Ground Maintenance

### Since when this issue started?

February 2022 still not resolved

### Issue Description?

There are missing bricks from the top of the brick pillar on the boundary wall on Loxford Lane that need cementing back in. The missing bricks are located in the garden area just behind the wall. Please undertake this repair asap
![75377B6F-451E-4A71-8F72-229C632281C7](https://user-images.githubusercontent.com/105227854/182806210-5cd32b5f-fb22-49da-99ee-17576450c2d8.jpeg)

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
This has now been logged with a contractor who will be attending shortly.

**Comment by jeremydoran** [comment]
This has now been completed.
