### ISSUE TITLE
Dumping by 129 blackthorn road 

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#42]
### Property Details

129 blackthorn road 

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

10 Aug 2022

### Issue Description?

There is a furniture dumped by someone living at 129 blackthorn road. 
please urgently let the owner know as resident were told last time yet it was dumped again. It should be removed in 3 days before we invoke fines. 

![57D58935-E3C8-4E0D-B5A9-C6CB4D8B617B](https://user-images.githubusercontent.com/85579935/184254794-b102206c-99bd-4f38-b2b2-c1164a8707e7.png)

video https://share.icloud.com/photos/036i0cQWfCpnZuJzLT9YZUWpg

### Logged By

Directors

**Comment by jeremydoran** [comment]
I have spoken with the Landlord this afternoon and advised that this needs to be removed asap. I have followed this up with an email and the landlord has advised he will speak to his tenant now.

**Comment by theparksilford** [comment]
Thanks. It’s been removed. Closing the issue.
