### ISSUE TITLE
Door issues Blackthorn road block 197-211

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#43]
### Property Details

197 blackthorn road 

### Type of problem?

General Issue

### Since when this issue started?

Long time 

### Issue Description?

There is a door issue where it’s not unlocking from flats. The buzzer is not heard  etc. multiple flats facing same issue. 

### Logged By

Directors

**Comment by theparksilford** [comment]
@humzaakhtar1 I have created the issue here.

**Comment by jeremydoran** [comment]
This has been logged and has been allocated to a contractor to attend asap.

**Comment by jeremydoran** [comment]
An engineer will be attending to this tomorrow morning.

**Comment by jeremydoran** [comment]
Pats have been required to resolved this issue, these have been on order for sometime. The required parts are due in on Friday 4th November and are scheduled to be fitted on the same day by the engineer.

**Comment by jeremydoran** [comment]
The parts were fitted and the intercom was tested and left working.
