### ISSUE TITLE
Leaking ceiling 

### ISSUE THREAD

**Issue by Blackthorn161** [theparksilford/Issues#44]
### Property Details

Block G 

### Contact Details

imocanurotaru@gmail.com 

### Type of problem?

Repair

### Since when this issue started?

14.08.2022

### Issue Description?

The water is leaking through the ceiling in the meter room and the water is seeping through the wall and the floor. It is a very high level of humidity and can be really dangerous for the whole block.

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
A plumber has been instruted to attend to this asap.

**Comment by jeremydoran** [comment]
This leak has now been fixed.
