### ISSUE TITLE
Lift making a creaking sound 

### ISSUE THREAD

**Issue by Blackthorn161** [theparksilford/Issues#45]
### Property Details

Block G 

### Contact Details

imocanurotaru@gmail.com 

### Type of problem?

Repair

### Since when this issue started?

19.09.2022

### Issue Description?

The lift from Block G makes noise sounds like clanking, screeching, squeaking. Abnormal noise usually signals a need for lift equipment maintenance. Kindly ask to call an lift repair expert to reduce further wear or damage to problematic mechanisms.

Issues like these can signal a serious problem and should never be ignored. To continue enjoying that convenience and to keep everyone safe  it’s important that the lift be properly cared for. 

Please take measures

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
Thank you for bringing this to our attention. I have asked the company that looks after the lift to attend to see what can be done to prevent any excess wear to the lift and to make sure that the lift is functioning correctly.

**Comment by jeremydoran** [comment]
Yes this will shared once the lift company have advised me.

**Comment by jeremydoran** [comment]
The lift company have advised that they will be attending to inspect the lift on 14.10.22.

**Comment by Blackthorn161** [comment]
Thank you!
