### ISSUE TITLE
Dumping by 3 cedar close

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#46]
### Property Details

3 cedar close

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

Last few months

### Issue Description?

3 cedar close have been dumping for some time and no judge worked with them. Please contact the property owner and let them know the issue. They are not allowed to use the bin room nor allowed to just dump whatever they want. Ask them to remove the carpet they dumped. See picture. 
![07959E9F-96E0-4E64-862B-C5432C79C3B6](https://user-images.githubusercontent.com/85579935/194566358-49c384ef-dbae-4076-80b6-3136bd3cca42.jpeg)

### Logged By

Directors

**Comment by jeremydoran** [comment]
This leaseholder has been notified.

**Comment by theparksilford** [comment]
The carpet still there in the floor by the bin. Please chase them.

**Comment by jeremydoran** [comment]
I'm not sure we have the write email address & we do not hold any contact telephone number for the landlord / resident. 
We will try to contact the resident once again.

**Comment by theparksilford** [comment]
Please write a letter to the residents.

**Comment by jeremydoran** [comment]
Letter has been sent in the post to the resident.

**Comment by theparksilford** [comment]
Closing this and hoping the letter would do the trick.
