### ISSUE TITLE
Dumping by L&Q residents 

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#48]
### Property Details

L&Q blocks 

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

12 Oct 2022

### Issue Description?

There have been lots of dumping by the bin L&Q maintains. Please ask them to get it cleared. 
![448D5705-8361-4B68-A133-730002FDA248](https://user-images.githubusercontent.com/85579935/197534286-45d85c74-60ac-4381-aea5-5e6f91946322.jpeg)

### Logged By

Directors

**Comment by jeremydoran** [comment]
L&Q have been notified and have asked that this gets collected asap.
