### ISSUE TITLE
Front door lock 

### ISSUE THREAD

**Issue by Blackthorn161** [theparksilford/Issues#49]
### Property Details

Block G 

### Contact Details

imocanurotaru@gmail.com 

### Type of problem?

Repair

### Since when this issue started?

One week ago

### Issue Description?

Hi,
I would like to let you know the lock on the main door is broken. The key is able to rotate the lock, but does not successfully lock or unlock the door. I'm afraid that in a short time a key will simply break in the lock or will remain stuck.

Emergency must be repaired, better to change it  with the new one, please. 

Thank you 

### Logged By

Leaseholder or FreeHolder

**Comment by Blackthorn161** [comment]
Thanks for the reply. We are looking forward to it.

**Comment by jeremydoran** [comment]
This repair was recently carried out.
Please let me know if there are still any issues with the doors.
