### ISSUE TITLE
Air brick missing

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#5]
### Property Details

1-15 Blackthorn road

### Type of problem?

Repair

### Since when this issue started?

Aug 2021

### Issue Description?

The airbrick is missing, this causes mouse infestation, Please get this fixed.
![image](https://user-images.githubusercontent.com/85579935/141960751-5aa97468-bc11-43c1-8ac1-7ae8a236ec2f.png)

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
RR Please update the status here.

**Comment by jeremydoran** [comment]
This was attended to yesterday and has now been resolved.
