### ISSUE TITLE
Main door intercom block A not working and door is left open.

### ISSUE THREAD

**Issue by togdheer** [theparksilford/Issues#50]
### Property Details

Block A 

### Contact Details

cruisecontroll@hotmail.com

### Type of problem?

Repair

### Since when this issue started?

Months ago

### Issue Description?

The intercom was reported as faulty months ago. A repair was attempted which lasted few lasted days. A few weeks ago another repair was attempted, the repairman said a new part would need to be ordered as the one in the door was beyond repair that was over a month ago.   The door is open 24/7.  

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
@jeremydoran why this issue opened for months? Are we aware the issue is not fixed. Are we waiting for something?

**Comment by jeremydoran** [comment]
This was repaired today and left in a working condition. 
Please report this again should the issue come back.
