### ISSUE TITLE
Rubbish bags blocking Communal bin store top of Blackthorn Road

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#51]
### Property Details

Blackthorn Road

### Contact Details

Rgthrow@gmail.com

### Type of problem?

Cleaning

### Since when this issue started?

21/12/2022

### Issue Description?

The bin store is full of bags of rubbish and the council have left the bins outside. Please instruct your grounds maintenance team to clear this bin store and any others when they come on Thursday 22 December
![Uploading 74E9F256-101E-44B2-9295-5B7AA9513BE2.jpeg…]()

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
This has been reported to the grounds maintenance team and also the council, the council will be attending this Friday 23rd December to remove all rubbish in the bin store areas.

**Comment by Thurgarton66** [comment]
The council refuse collectors have not emptied the communal bin stores and
have just lest the bins outside.

Please ask the grounds maintenance team to empty the bin stores.

**Comment by Thurgarton66** [comment]
This applies to all the bin stores on the estate where there is the same
problem

**Comment by jeremydoran** [comment]
This has been reported to the council and the grounds maintenance team to attend to.
