### ISSUE TITLE
Bin Store Block A over flowing 

### ISSUE THREAD

**Issue by togdheer** [theparksilford/Issues#52]
### Property Details

Block A bin store room over flowing with rubbish

### Contact Details

Cruisecontroll@hotmail.com

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

28/12/2022

### Issue Description?

People have dumped some light furniture inside the bin store leading to some of the bins  not being accessible. Some people including some of the houses have just laid their rubbish on the ground inside and outside the store leading to a pileup. 

Iconic came last Thursday (29 Dec), am not sure what they did in this particular bin store. The council came to collect the refuse on Friday (30 Dec) and did not deal with this store when they saw the state it was in. 

The next refuse collection on the Redbridge website is Jan 4th.   

     

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
The grounds maintenance team and the council have been notified.

**Comment by theparksilford** [comment]
Issue resolved
