### ISSUE TITLE
Bin room usage by 45 blackthorn road

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#53]
### Property Details

41 blackthorn road

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

Few months

### Issue Description?

45 blackthorn road is continuously use the bin room. The bins are off limits to houses. Please let them know that they should not the bin rooms. Also, they should get the bins for houses from council if they don’t have already. If they need more bins because if big family, they should contact council and they will provide either a big one or multiple bins. 
Any future usage of the bin rooms will be fined. 
video https://share.icloud.com/photos/0bcx_9fYCWpi-Di6DFH8TpSww

![9EEE2CEA-2E33-48A8-80DD-B20C9E97B62E](https://user-images.githubusercontent.com/85579935/211419380-c0776b1e-7554-4e59-81c7-acc652781b34.jpeg)

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
The owners have been notified and have been told to stop doing this immediately.
