### ISSUE TITLE
Bin room usage by 57 blackthorn road 

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#54]
### Property Details

57 blackthorn road 

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

Few months 

### Issue Description?

The guys living at 57 keep using the bin room and don’t care what’s the state of the bin room. Please advise the owners to get this fixed as a last warning. There is zero tolerance for bulk rubbish and bin usage. 
houses should use their bins and contract council if they need more bins. 
Video https://share.icloud.com/photos/051U3FCCf2l3G_vOZ1RqJYjBQ

![27231318-6B74-47B4-8645-6BEE018E4055](https://user-images.githubusercontent.com/85579935/211426921-b09bc735-03eb-49ed-ae46-c1423e67436a.jpeg)

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
The owners have been notified and have been told to stop doing this immediately.

**Comment by theparksilford** [comment]
Now they dumped an office chair. I have sent it back to their house. This is not stopping. Please complain the owner again and remind him that next time a fine will be on the way.

**Comment by jeremydoran** [comment]
Spoken with the owner who is going to call the tenant and speak with them and advised that this is not acceptable.
