### ISSUE TITLE
3 cedar close usage of bin room

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#56]
### Property Details

3 cedar close

### Type of problem?

Bulk Rubbish/Dumping

### Since when this issue started?

A year

### Issue Description?

This has been going on for ages now. They have been told many times but the penny not dropping. Please contact the owners of the 3 cedar close and ask them if they want to pay for bin rooms maintenance and other costs associated with it as houses are not allowed to use bin. 3 Cedar got 2 bins yet they produce huge amount of garbage and dump other bill rubbish. This needs to end now  and urgently. 

Video https://share.icloud.com/photos/080BDqU2Hh2IPeN5Z6NRGhcRg

![89112B0C-0B6B-48C8-B3D1-CDC60854560C](https://user-images.githubusercontent.com/85579935/212107106-1a849c05-0adf-4b72-8fd1-a05091bb7340.jpeg)

### Logged By

Directors

**Comment by jeremydoran** [comment]
We have now tried to contact the owner of this property however it appears that the email address we hold on the system is not valid and we no not hold a contact telephone number.  We have tried to contact this owner before. 
We will send out a letter however this can take sometime as this needs to be posted.

**Comment by theparksilford** [comment]
Please write to the resident and tell them in strong words.

**Comment by jeremydoran** [comment]
A letter will be sent to the resident shortly advising to stop fly tipping.

**Comment by jeremydoran** [comment]
A strongly worded letter that been sent in today's post to this resident.
