### ISSUE TITLE
2 Blackthorn road resident issue

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#57]
### Property Details

2 blackthorn road 

### Type of problem?

Cleaning

### Since when this issue started?

Few months

### Issue Description?

It’s been many time the guy from 2 Blackthorn is involved in anti social behaviour. He parks in bock G parking and smoke for hours and piss on the grass and make mess. This has to stop. Please contact the owner of 2 Blackthorn road that this is not acceptable and we will start Charing him for cleaning and report to council/police. 

### Logged By

Directors

**Comment by jeremydoran** [comment]
The owner has been contacted, the owner of the property is L&Q.

**Comment by jeremydoran** [comment]
L&Q were contacted yesterday and a formal complaint was raised. 
The resident has been contacted about this and I have asked L&Q to keep me updated.

**Comment by jeremydoran** [comment]
The property manager from L&Q has been contacted about this and the littering that has taken place recently.

**Comment by sadurrani** [comment]
close for time being, we will wait for next time
