### ISSUE TITLE
Dumped rubbish in front of 16 Blackthorn Road by property cleaner

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#58]
### Property Details

16 Blackthorn Road

### Contact Details

Thurgarton66

### Type of problem?

Cleaning

### Since when this issue started?

7 August 2023

### Issue Description?

16 Blackthorn Road has been vacated and the property cleaned. The cleaner has left rubbish piled high in front of the property up to 6 feet high. Please either get the landlord to remove it or charge them for removal without adding to our service charge

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
I have spoken with the landlord this afternoon, he has passed my details on to his letting agent Ebenezer and will be attending the property Saturday morning to arrange for the items to be removed.

**Comment by sadurrani** [comment]
close, it was resolved
