### ISSUE TITLE
Door handle broken

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#6]
### Property Details

81 Blackthorn Road

### Type of problem?

Repair

### Since when this issue started?

Oct 2021

### Issue Description?

The door handle is broken, the screw is visible but its dangerous poking out and could cause issues.
![image](https://user-images.githubusercontent.com/85579935/141962128-2b46d6a7-23a9-4278-96b0-41111658040a.png)

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
A contractor has attended and has advised that he has been unable to find a suitable door handle replacement in the same size and colour that is in stock. I have spoken to the contractor today who will be looking to source something similar.

**Comment by jeremydoran** [comment]
I have requested an urgent update on this.

**Comment by jeremydoran** [comment]
The contractor has attended today and fixed a new door handle. 

This is a slightly different size to the original handle as the same size handle could not not be purchased.
