### ISSUE TITLE
Block G Roofing issue

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#7]
### Property Details

Block G

### Type of problem?

Repair

### Since when this issue started?

Aug 2021

### Issue Description?

There are issues with the roof in Block G. The water damage is making life difficult for the residents. We have got survey done which shows damager to the ridge. We have got few contractors and one seems to be good with the price. Antonio/Usman will provide the details and we want RR to talk to the contractor, make it official and get the proper work document and make sure it convers all the bases. Once this done which shouldnt take long, we want to give go ahead as it would need scaffolding and few weeks of work.

### Logged By

Leaseholder or FreeHolder

**Comment by jeremydoran** [comment]
I have now contacted S&V Roofing and have asked for a formal quote to be submitted. I will then be able to vet this contractor accordingly.

**Comment by jeremydoran** [comment]
S & V Roofing have now been formally instructed to carry out the roof works as required. They will be providing us with a start date shortly with when the works can commence. The works will start sometime in December. An update will be provided shortly.

**Comment by jeremydoran** [comment]
S & V Roofing have confirmed a start date of Monday 6th December 2021.

The scaffolding being erected around the building followed by the roof works, a letter has been sent out to all the residents to advise. 

These works should take 3 to 4  weeks from start to completion.

**Comment by jeremydoran** [comment]
S & V Roofing have now confirmed that this work has been completed and the scaffolding will be taken down over the next couple of days.
