### ISSUE TITLE
Block G Mould problem

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#8]
### Property Details

Block G

### Contact Details

Nida

### Type of problem?

Repair

### Since when this issue started?

Oct 2021

### Issue Description?

The moulds that is spreading fast I noticed near the door to the lift. This can be highly dangerous to clinically vulnerable people in our block especially with asthma, children and babies. Please have someone sent and have it checked and treat it.

![image](https://user-images.githubusercontent.com/85579935/142045962-09fdec43-6e59-4dae-b9fc-0b2364f594d3.png)
![image](https://user-images.githubusercontent.com/85579935/142046065-29daa64e-5f53-4a73-87db-9e37fe7956f1.png)

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
Please check if this is due to Roof leaking issue or some other problem. If we are sure that its due to the Roof then the issue #7 should be expedited to get the roofing fixed.

**Comment by jeremydoran** [comment]
This has been checked by a contractor who has advised that this may be due to the issues with the roof with water coming down the cavity of the walls, the contractor has advised that it is best to get the roof issue resolved in the first instance.

**Comment by jeremydoran** [comment]
The roof works have been formally instructed and are due to take place in December, once the roof works have been completed we can look to address this problem with the mould as the issue might be connected to the leaking roof issue.

**Comment by jeremydoran** [comment]
Now the roof works have been completed a contractor has been instructed to attend to open up the ceiling voids to inspect and treat this mould issue on the ground floor.

**Comment by jeremydoran** [comment]
The contractor has been contacted for an update on this.

**Comment by jeremydoran** [comment]
The contractor has today advised that he will be going to the development by the end of this week to start with the investigation works regarding this mould issue.

**Comment by jeremydoran** [comment]
We have now appointed a new contractor to take a look at this as this has been ongoing for sometime. 
The new contractor will be attending to inspect this mould problem this afternoon.

**Comment by jeremydoran** [comment]
The new contractor who we appointed to look at this did attend this week as planned, I have chased for a report / feedback which will be send across to me soon. I will share this with everyone once I'm in receipt of this.

**Comment by jeremydoran** [comment]
The contractor is going to inspect this today and provide feedback / a report.

**Comment by jeremydoran** [comment]
The engineer attended site for further investigation. Please see his report;

He removed a section of plasterboard to gain access to the void, and found no pipes or damp in the plasterboard just electrical cables.
Temporary fixed batten to plasterboard and fixed back plasterboard.
As there is no pipes in the boxing in we believe this is a ventilation problem causing the mould.
The flats are providing heat, and the communal areas have air vents in which are blowing cold air and causing condensation.

**Comment by jeremydoran** [comment]
The contractor is at the development today to carry out the following remedy works below:

Cut out existing ceiling investigation hole 400 by 400mm and fit one number vent grill to allow air circulation.
Fill plaster , make good and good hole on the stairs
Clean the communal ceiling with mould cleaner
Apply stain block
Apply 2No coats of emulsion to 5m down the communal ground floor entrance and inspection hole made in stairwell.

If this work is not finished today then the contractor will return next week to finish this.

**Comment by jeremydoran** [comment]
The contractor has advised me that this job is now completed with the vent that has been installed and the decoration works completed.

**Comment by theparksilford** [comment]
Thanks. Closing this issue as this seems to be fixed. If this happens again then we would look again.  Closing it now
