### ISSUE TITLE
91 Backyard cleaning and light issue

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#9]
### Property Details

91 Blackthorn Road

### Type of problem?

Repair

### Since when this issue started?

July 2021

### Issue Description?

The light is not working and the backyard area got plans/trees not looked after.. Both are Parks common areas so it should be maintained by the Parks/Management Agent.

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment]
please contact the resident and ask for latest and see what we need to do for their issue and update here. Thanks.

**Comment by theparksilford** [comment]
I talked to the home owner, the back alley got cleared out by Iconic, just need to resolved the light issue. Please contact them and arrange a visit

**Comment by jeremydoran** [comment]
I have now contacted the home owner about this issue to see if this matter has been resolved or if this is still an issue. I will provide an update once I know more.

**Comment by jeremydoran** [comment]
Our contractor has advised that this issue has now been resolved.
